### PR TITLE
Cleanup code

### PR DESCRIPTION
**Pull request by AaronLi**

### CODE REVIEW

**Comment by tpt5cu** [comment]
Why were the changes in KeyPress made? I'm leaving PID in the V_2 version because I'm going to be making changes to it later.

**Comment by AaronLi** [comment]
> Why were the changes in KeyPress made? I'm leaving PID in the V_2 version because I'm going to be making changes to it later.

The changes to key press are to make the code more concise and readable. It also drops the getattr call for a built in pygame function that does the same thing but more descriptively.

**Comment by tpt5cu** [comment]
I don't have a whole lot of experience with pyevent. Have you tested this?

**Comment by AaronLi** [comment]
yeah, running KeyPress.py works as before. Everything should be functionally the same

**Comment by tpt5cu** [comment]
Awesome cool, just wanted to double check hahah. I'll approve.

**Pull request merged**
